"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.2
  Module: unitree_api.msg.dds_
  IDL file: RequestHeader_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass, field

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
# import unitree_api

from unitree_dds_wrapper.idl import unitree_api

@dataclass
@annotate.final
@annotate.autoid("sequential")
class RequestHeader_(idl.IdlStruct, typename="unitree_api.msg.dds_.RequestHeader_"):
    identity: 'unitree_dds_wrapper.idl.unitree_api.msg.dds_.RequestIdentity_' = field(default_factory=lambda: unitree_api.msg.dds_.RequestIdentity_())
    lease: 'unitree_dds_wrapper.idl.unitree_api.msg.dds_.RequestLease_' = field(default_factory=lambda: unitree_api.msg.dds_.RequestLease_())
    policy: 'unitree_dds_wrapper.idl.unitree_api.msg.dds_.RequestPolicy_' = field(default_factory=lambda: unitree_api.msg.dds_.RequestPolicy_())


