"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: unitree_go.msg.dds_
  IDL file: LidarState_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass, field

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

@dataclass
@annotate.final
@annotate.autoid("sequential")
class LidarState_(idl.IdlStruct, typename="unitree_go.msg.dds_.LidarState_"):
    stamp: types.float64 = field(default_factory=lambda: 0.0)
    firmware_version: str = field(default_factory=lambda: "")
    software_version: str = field(default_factory=lambda: "")
    sdk_version: str = field(default_factory=lambda: "")
    sys_rotation_speed: types.float32 = field(default_factory=lambda: 0.0)
    com_rotation_speed: types.float32 = field(default_factory=lambda: 0.0)
    error_state: types.uint8 = field(default_factory=lambda: 0)
    dirty_percentage: types.uint8 = field(default_factory=lambda: 0)
    cloud_frequency: types.float32 = field(default_factory=lambda: 0.0)
    cloud_packet_loss_rate: types.float32 = field(default_factory=lambda: 0.0)
    cloud_size: types.uint32 = field(default_factory=lambda: 0)
    cloud_scan_num: types.uint32 = field(default_factory=lambda: 0)
    imu_frequency: types.float32 = field(default_factory=lambda: 0.0)
    imu_packet_loss_rate: types.float32 = field(default_factory=lambda: 0.0)
    imu_rpy: types.array[types.float32, 3] = field(default_factory=lambda: [0, 0, 0])
    serial_recv_stamp: types.float64 = field(default_factory=lambda: 0.0)
    serial_buffer_size: types.uint32 = field(default_factory=lambda: 0)
    serial_buffer_read: types.uint32 = field(default_factory=lambda: 0)


