"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: unitree_go.msg.dds_
  IDL file: MotorState_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass, field

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

@dataclass
@annotate.final
@annotate.autoid("sequential")
class MotorState_(idl.IdlStruct, typename="unitree_go.msg.dds_.MotorState_"):
    mode: types.uint8 = field(default_factory=lambda: 0)
    q: types.float32 = field(default_factory=lambda: 0)
    dq: types.float32 = field(default_factory=lambda: 0)
    ddq: types.float32 = field(default_factory=lambda: 0)
    tau_est: types.float32 = field(default_factory=lambda: 0)
    q_raw: types.float32 = field(default_factory=lambda: 0)
    dq_raw: types.float32 = field(default_factory=lambda: 0)
    ddq_raw: types.float32 = field(default_factory=lambda: 0)
    temperature: types.uint8 = field(default_factory=lambda: 0)
    lost: types.uint32 = field(default_factory=lambda: 0)
    reserve: types.array[types.uint32, 2] = field(default_factory=lambda: [0, 0])


