"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: unitree_hg.msg.dds_
  IDL file: HandState_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass, field

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
from unitree_dds_wrapper.idl import unitree_hg


@dataclass
@annotate.final
@annotate.autoid("sequential")
class HandState_(idl.IdlStruct, typename="unitree_hg.msg.dds_.HandState_"):
    motor_state: types.sequence['unitree_dds_wrapper.idl.unitree_hg.msg.dds_.MotorState_'] = field(default_factory=lambda: [])
    press_sensor_state: types.sequence['unitree_dds_wrapper.idl.unitree_hg.msg.dds_.PressSensorState'] = field(default_factory=lambda: [])
    imu_state: 'unitree_dds_wrapper.idl.unitree_hg.msg.dds_.IMUState_' = field(default_factory=lambda: unitree_hg.msg.dds_.IMUState_())
    power_v: types.float32 = field(default_factory=lambda: 0.0)
    power_a: types.float32 = field(default_factory=lambda: 0.0)
    system_v: types.float32 = field(default_factory=lambda: 0.0)
    device_v: types.float32 = field(default_factory=lambda: 0.0)
    error: types.array[types.uint32, 2] = field(default_factory=lambda: [0, 0])
    reserve: types.array[types.uint32, 2] = field(default_factory=lambda: [0, 0])


