"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: std_msgs.msg.dds_
  IDL file: Header_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass, field

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

from unitree_dds_wrapper.idl import builtin_interfaces

@dataclass
@annotate.final
@annotate.autoid("sequential")
class Header_(idl.IdlStruct, typename="std_msgs.msg.dds_.Header_"):
    stamp: 'unitree_dds_wrapper.idl.builtin_interfaces.msg.dds_.Time_' = field(default_factory=lambda: builtin_interfaces.msg.dds_.Time_())
    frame_id: str = field(default_factory=lambda: "")


