"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: unitree_z1.msg.dds_
  IDL file: GripperCommand_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass, field

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import unitree_z1


@dataclass
@annotate.final
@annotate.autoid("sequential")
class GripperCommand_(idl.IdlStruct, typename="unitree_z1.msg.dds_.GripperCommand_"):
    position: types.float32 = field(default_factory=lambda: 0.0)
    max_effort: types.float32 = field(default_factory=lambda: 0.0)


