"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: unitree_z1.msg.dds_
  IDL file: Pose_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass, field

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import unitree_z1


@dataclass
@annotate.final
@annotate.autoid("sequential")
class Pose_(idl.IdlStruct, typename="unitree_z1.msg.dds_.Pose_"):
    position: types.array[types.float64, 3] = field(default_factory=lambda: [0.0, 0.0, 0.0])
    orientation: types.array[types.float64, 4] = field(default_factory=lambda: [1.0, 0.0, 0.0, 0.0])


