"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: unitree_z1.msg.dds_
  IDL file: Twist_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass, field

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import unitree_z1


@dataclass
@annotate.final
@annotate.autoid("sequential")
class Twist_(idl.IdlStruct, typename="unitree_z1.msg.dds_.Twist_"):
    linear: types.array[types.float64, 3] = field(default_factory=lambda: [0.0, 0.0, 0.0])
    angular: types.array[types.float64, 3] = field(default_factory=lambda: [0.0, 0.0, 0.0])


