"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: unitree_hg.msg.dds_
  IDL file: LowCmd_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass, field

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
from unitree_dds_wrapper.idl import unitree_hg


@dataclass
@annotate.final
@annotate.autoid("sequential")
class LowCmd_(idl.IdlStruct, typename="unitree_hg.msg.dds_.LowCmd_"):
    mode_pr: types.uint8 = field(default_factory=lambda: 0)
    mode_machine: types.uint8 = field(default_factory=lambda: 0)
    motor_cmd: types.array['unitree_dds_wrapper.idl.unitree_hg.msg.dds_.MotorCmd_', 35] = field(default_factory=lambda: [unitree_hg.msg.dds_.MotorCmd_() for _ in range(35)])
    reserve: types.array[types.uint32, 4] = field(default_factory=lambda: [0, 0, 0 ,0])
    crc: types.uint32 = field(default_factory=lambda: 0)