"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: unitree_hg.msg.dds_
  IDL file: MotorCmd_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass, field

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types

@dataclass
@annotate.final
@annotate.autoid("sequential")
class MainBoardState_(idl.IdlStruct, typename="unitree_hg.msg.dds_.MainBoardState_"):
    fan_state: types.array[types.uint16, 6] = field(default_factory=lambda: [0, 0, 0, 0, 0, 0])
    temperature: types.array[types.int16, 6] = field(default_factory=lambda: [0, 0, 0, 0, 0, 0])
    value: types.array[types.float32, 6] = field(default_factory=lambda: [0., 0., 0., 0., 0., 0.])
    state: types.array[types.uint32, 6] = field(default_factory=lambda: [0, 0, 0, 0, 0, 0])