"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: unitree_hg.msg.dds_
  IDL file: PressSensorState_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass, field

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types

@dataclass
@annotate.final
@annotate.autoid("sequential")
class PressSensorState_(idl.IdlStruct, typename="unitree_hg.msg.dds_.PressSensorState"):
    pressure: types.array[types.float32, 12] = field(default_factory=lambda: [0.0 for _ in range(12)])
    temperature: types.array[types.float32, 12] = field(default_factory=lambda: [0.0 for _ in range(12)])
    lost: types.uint32 = field(default_factory=lambda: 0)
    reserve: types.uint32 = field(default_factory=lambda: 0)


