"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: unitree_go.msg.dds_
  IDL file: HeightMap_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass, field

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

@dataclass
@annotate.final
@annotate.autoid("sequential")
class HeightMap_(idl.IdlStruct, typename="unitree_go.msg.dds_.HeightMap_"):
    stamp: types.float64 = field(default_factory=lambda: 0.0)
    frame_id: str = field(default_factory=lambda: "")
    resolution: types.float32 = field(default_factory=lambda: 0.0)
    width: types.uint32 = field(default_factory=lambda: 0)
    height: types.uint32 = field(default_factory=lambda: 0)
    origin: types.array[types.float32, 2] = field(default_factory=lambda: [0.0, 0.0])
    data: types.sequence[types.float32] = field(default_factory=lambda: [])


