"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: unitree_hx.msg.dds_
  IDL file: BmsCmd_hx.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass, field

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

@dataclass
@annotate.final
@annotate.autoid("sequential")
class BmsCmd_(idl.IdlStruct, typename="unitree_hx.msg.dds_.BmsCmd_"):
    cmd: types.uint8 = field(default_factory=lambda: 0)
    reserve: types.array[types.uint8, 40] = field(default_factory=lambda: [ 0 for _ in range(40)])