"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: geometry_msgs.msg.dds_
  IDL file: TwistWithCovariance_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass, field

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

from unitree_dds_wrapper.idl import geometry_msgs

@dataclass
@annotate.final
@annotate.autoid("sequential")
class TwistWithCovariance_(idl.IdlStruct, typename="geometry_msgs.msg.dds_.TwistWithCovariance_"):
    twist: 'unitree_dds_wrapper.idl.geometry_msgs.msg.dds_.Twist_' = field(default_factory=lambda: geometry_msgs.msg.dds_.Twist_())
    covariance: types.array[types.float64, 36] = field(default_factory=lambda: types.array(types.float64, 36)())


