"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: nav_msgs.msg.dds_
  IDL file: OccupancyGrid_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass, field

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
# import nav_msgs

# if TYPE_CHECKING:
#      import std_msgs.msg.dds_

from unitree_dds_wrapper.idl import std_msgs, nav_msgs

@dataclass
@annotate.final
@annotate.autoid("sequential")
class OccupancyGrid_(idl.IdlStruct, typename="nav_msgs.msg.dds_.OccupancyGrid_"):
    header: 'unitree_dds_wrapper.idl.std_msgs.msg.dds_.Header_' = field(default_factory=lambda: std_msgs.msg.dds_.Header_())
    info: 'unitree_dds_wrapper.idl.nav_msgs.msg.dds_.MapMetaData_' = field(default_factory=lambda: nav_msgs.msg.dds_.MapMetaData_())
    data: types.sequence[types.uint8] = field(default_factory=lambda: types.sequence(types.uint8, 0))


