"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: builtin_interfaces.msg.dds_
  IDL file: Duration_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass, field

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

@dataclass
@annotate.final
@annotate.autoid("sequential")
class Duration_(idl.IdlStruct, typename="builtin_interfaces.msg.dds_.Duration_"):
    sec: types.int32 = field(default_factory=lambda: 0)
    nanosec: types.uint32 = field(default_factory=lambda: 0)


