"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: nav_msgs.msg.dds_
  IDL file: Odometry_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass, field

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

from unitree_dds_wrapper.idl import geometry_msgs, std_msgs

@dataclass
@annotate.final
@annotate.autoid("sequential")
class Odometry_(idl.IdlStruct, typename="nav_msgs.msg.dds_.Odometry_"):
    header: 'unitree_dds_wrapper.idl.std_msgs.msg.dds_.Header_' = field(default_factory=lambda: std_msgs.msg.dds_.Header_())
    child_frame_id: str = field(default_factory=lambda: "")
    pose: 'unitree_dds_wrapper.idl.geometry_msgs.msg.dds_.PoseWithCovariance_' = field(default_factory=lambda: geometry_msgs.msg.dds_.PoseWithCovariance_())
    twist: 'unitree_dds_wrapper.idl.geometry_msgs.msg.dds_.TwistWithCovariance_' = field(default_factory=lambda: geometry_msgs.msg.dds_.TwistWithCovariance_())


