"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: builtin_interfaces.msg.dds_

"""

from ._Time_ import Time_
from ._Duration_ import Duration_
__all__ = ["Time_", "Duration_", ]
